// Code generated by ent, DO NOT EDIT.

package ent

import (
	"projectzero/ent/schema"
	"projectzero/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescNickName is the schema descriptor for nick_name field.
	userDescNickName := userFields[1].Descriptor()
	// user.DefaultNickName holds the default value on creation for the nick_name field.
	user.DefaultNickName = userDescNickName.Default.(string)
	// userDescUserType is the schema descriptor for user_type field.
	userDescUserType := userFields[3].Descriptor()
	// user.DefaultUserType holds the default value on creation for the user_type field.
	user.DefaultUserType = userDescUserType.Default.(int)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[4].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int)
	// userDescCreateAt is the schema descriptor for create_at field.
	userDescCreateAt := userFields[6].Descriptor()
	// user.DefaultCreateAt holds the default value on creation for the create_at field.
	user.DefaultCreateAt = userDescCreateAt.Default.(int64)
	// userDescUpdateAt is the schema descriptor for update_at field.
	userDescUpdateAt := userFields[7].Descriptor()
	// user.DefaultUpdateAt holds the default value on creation for the update_at field.
	user.DefaultUpdateAt = userDescUpdateAt.Default.(int64)
}
